spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:TASKDB
    username: taskapp
    password: password123
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 10

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true

# Logging configuration for development
logging:
  level:
    com.taskmanagement.backend: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
